name: website

on:
  workflow_dispatch:
  push:
    paths:
      - "example/**"
  pull_request:
    paths:
      - "example/**"

jobs:
  build-website:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./example
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@v1
        with:
          mdbook-version: "latest"

      - name: Download mdbook-catppuccin
        run: |
          curl -sSL ${{ env.RELEASE_URL }}/${{ env.TARGET }}.tar.gz | tar -xz
          echo `pwd`/${{ env.TARGET }} >> $GITHUB_PATH
        env:
          RELEASE_URL: "https://github.com/catppuccin/mdBook/releases/latest/download"
          TARGET: "mdbook-catppuccin-x86_64-unknown-linux-gnu"

      - name: Build mdBook
        run: |
          mdbook-catppuccin install
          mdbook build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./example/book
          exclude_assets: ".github,**/.gitignore"
